name: Package Application for Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
      steps:
      - uses: actions/checkout@v2
      - name: InstallRequirements
        run: python -m pip install -r requirements.txt
      - name: Build-MacOS
        run: flet pack -n "MLV Dump UI" -i .\resources\ml_logo.ico --add-data ".\src\mlv_dump_ui\bin;bin" .\src\mlv_dump_ui\main.py
